version: '2.0'

services:
  redis:
    image: redis:latest
    container_name: rest-redis 
    hostname: rest-redis 

  gateway:
    build: 
      context: ./gateway
      # Default is blank which is equivalent to Dockerfile
      dockerfile: $DOCKERFILE 
    container_name: rest-gateway
    hostname: rest-gateway.kaazing.com
    image: rest-gateway
    links:
      - redis:rest-redis
    environment:
      #MAXHEAP: -Xmx4g
      # Use the non-verbose one for perf testing
      # LOG4JFILE: log4j-config-verbose.xml
      LOG4JFILE: log4j-config-not-verbose.xml
      #GATEWAY_ROLE: cloud
      GATEWAY_OPTS: -Dgateway.host=rest-gateway.kaazing.com -Dredis.host=rest-redis
    #command: gateway.start --config conf/gateway-config-kwic-cloud-perf.xml
