#!/bin/bash

if [ "$1" == "-rebuild" ]; then
  REBUILD=true
fi

docker-compose stop
docker-compose kill
docker-compose rm -afv

if [ "$REBUILD" == "true" ]; then
  docker rmi -f `docker images | grep step1_ | awk '{ print $3 }'`
fi
docker-compose build
