version: '2.0'

services: 
  # Once it is running:
  # docker exec es_echo ifconfig | grep addr (to find the IP)
  # Edit /etc/hosts to put hostname echo in IP
  #
  # Test in browser
  # Go to http://echo:8000 and test echo service.
  es_echo:
    build:
      context: node
    container_name: es_echo 
    hostname: echo
    image: es_echo
    # Uncomment the next two lines to get verbose logging on echo requests
    environment:
      GATEWAY_OPTS: -DLOG4J_CONFIG=/kaazing-gateway/conf/log4j-trace-transport-config.xml -Dgateway.hostname=echo
      #GATEWAY_OPTS: -Dgateway.hostname=echo
