#!/bin/bash
CONTS=`docker ps --filter status=dead --filter status=exited -aq`
if [ ! -z "$CONTS" ]; then
  docker stop $CONTS
  docker rm $CONTS
  echo Done cleaning up.
else
  echo No containers to clean up.
fi
